apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rails-hello-world.fullname" . }}-secrets
  labels:
    {{- include "rails-hello-world.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key-base: {{ .Values.rails.env.SECRET_KEY_BASE | b64enc | quote }}
  {{- if .Values.postgresql.azure.enabled }}
  postgres-password: {{ .Values.postgresql.azure.password | b64enc | quote }}
  {{- end }} 