name: Terraform Pipeline Template

on:
  workflow_call:
    inputs:
      env_dir:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: "Deploy Infrastructure"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_dir }}
    defaults:
      run:
        shell: bash
        working-directory: terraform/environment/${{ inputs.env_dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Bootstrap remote backend
        run: bash ../../scripts/bootstrap-remote-backend.sh

      - name: Debug Environment Variables
        run: |
          echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
          echo "ARM_TENANT_ID: $ARM_TENANT_ID"
          echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
          echo "AZURE_CLIENT_ID: $AZURE_CLIENT_ID"
          echo "AZURE_TENANT_ID: $AZURE_TENANT_ID"
          echo "AZURE_SUBSCRIPTION_ID: $AZURE_SUBSCRIPTION_ID"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'workflow_call' || github.event_name == 'push'
        run: terraform apply -auto-approve tfplan

      - name: Logout Azure
        if: always()
        run: az logout
