name: Terraform Pipeline Template

on:
  workflow_call:
    inputs:
      env_dir:
        required: true
        type: string

permissions:
  contents: read

jobs:
  terraform:
    name: "Deploy Infrastructure"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_dir }}
    defaults:
      run:
        shell: bash
        working-directory: terraform/environment/${{ inputs.env_dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Bootstrap remote backend
        run: bash ../../scripts/bootstrap-remote-backend.sh

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'workflow_call' || github.event_name == 'push'
        run: terraform apply -auto-approve tfplan

      - name: Logout Azure
        if: always()
        run: az logout
